# Generated by Django 2.2.10 on 2020-02-17 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.TextField()),
                ('position_on_main_building', models.IntegerField()),
                ('parking_facility_adjacency', models.BooleanField()),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Location')),
                ('purpose_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Purpose')),
                ('room_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.RoomType')),
            ],
        ),
    ]
